#!/usr/bin/env python3
"""
Interactive script to help set up your .env file for eBay API access.
"""

import os


def create_env_file():
    """Interactive setup for .env file."""
    print("="*60)
    print("eBay API Environment Setup")
    print("="*60)
    print()
    print("This script will help you create your .env file.")
    print()
    
    # Check if .env already exists
    if os.path.exists('.env'):
        print("⚠️  WARNING: .env file already exists!")
        response = input("Do you want to overwrite it? (yes/no): ").strip().lower()
        if response not in ['yes', 'y']:
            print("Setup cancelled.")
            return
        print()
    
    print("You'll need the following from https://developer.ebay.com/:")
    print("1. OAuth Token (required)")
    print("2. Client ID (optional)")
    print("3. Client Secret (optional)")
    print()
    print("Press Enter to skip optional fields.")
    print()
    
    # Get OAuth token (required)
    print("=" * 60)
    print("STEP 1: Get OAuth Token")
    print("=" * 60)
    print("Go to: https://developer.ebay.com/my/auth/?env=sandbox&index=0")
    print("1. Sign in with your eBay developer account")
    print("2. Click 'Get a User Token'")
    print("3. Copy the generated token")
    print()
    
    oauth_token = input("Paste your OAuth Token (required): ").strip()
    
    if not oauth_token:
        print("\n❌ OAuth token is required! Setup cancelled.")
        return
    
    # Get optional fields
    print()
    client_id = input("Enter your Client ID (optional, press Enter to skip): ").strip()
    client_secret = input("Enter your Client Secret (optional, press Enter to skip): ").strip()
    
    # Choose environment
    print()
    print("Choose environment:")
    print("  1. sandbox (for testing with limited data)")
    print("  2. production (for real data, uses API quota)")
    env_choice = input("Enter 1 or 2 [default: 1]: ").strip()
    environment = "production" if env_choice == "2" else "sandbox"
    
    # Create .env content
    env_content = f"""# eBay API Credentials
# Generated by setup_env.py

# OAuth Token (REQUIRED)
EBAY_OAUTH_TOKEN={oauth_token}

# Environment: sandbox or production
EBAY_ENVIRONMENT={environment}
"""
    
    # Add optional fields if provided
    if client_id:
        env_content += f"\n# Client ID (optional)\nEBAY_CLIENT_ID={client_id}\n"
    
    if client_secret:
        env_content += f"\n# Client Secret (optional)\nEBAY_CLIENT_SECRET={client_secret}\n"
    
    # Add placeholders for other fields
    env_content += """
# Optional fields (not required for basic usage)
# EBAY_APP_ID=your_app_id_here
# EBAY_REDIRECT_URI=your_redirect_uri_here
"""
    
    # Write to file
    try:
        with open('.env', 'w', encoding='utf-8') as f:
            f.write(env_content)
        
        print()
        print("="*60)
        print("✅ Success! Your .env file has been created.")
        print("="*60)
        print()
        print(f"Environment: {environment}")
        print(f"OAuth Token: {oauth_token[:20]}...{oauth_token[-10:]}")
        print()
        print("Next steps:")
        print("1. Test your setup: python example_usage.py")
        print("2. Collect data: python collect_ebay_data.py")
        print()
        print("Note: OAuth tokens expire after a few hours.")
        print("If you get authentication errors, generate a new token and run this script again.")
        
    except Exception as e:
        print(f"\n❌ Error creating .env file: {e}")


def main():
    """Main function."""
    try:
        create_env_file()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")


if __name__ == "__main__":
    main()


